"""The clipboard, borrowed and given back whole.

Pasting is still the most compatible way to put text into an arbitrary app,
so Halo sometimes has to use the clipboard. It used to save and restore only
plain text (pyperclip), which quietly destroyed whatever else you had copied:
an image became nothing, a Finder file copy became nothing, rich text lost its
formatting. This keeps every item on the general pasteboard with every type
each item offers -- plain and rich text, HTML, URLs, images, file references,
and app-private types -- and puts all of it back.

Two rules on the way back:

  - Restore only if the pasteboard is still ours. If its changeCount moved
    after Halo wrote, something else copied in the meantime (you did, or an
    app did), and restoring would overwrite that newer copy.
  - What Halo writes is marked transient and concealed (nspasteboard.org
    conventions), so clipboard managers do not record your dictation into
    their history on the way through.

Every function takes the pasteboard as an argument so the tests can run on a
private, uniquely named pasteboard and never touch yours.
"""
from dataclasses import dataclass

TRANSIENT = "org.nspasteboard.TransientType"
CONCEALED = "org.nspasteboard.ConcealedType"
AUTO_GENERATED = "org.nspasteboard.AutoGeneratedType"
PLAIN = "public.utf8-plain-text"


def general():
    from AppKit import NSPasteboard
    return NSPasteboard.generalPasteboard()


@dataclass
class Snapshot:
    items: list            # [[(type, bytes), ...], ...] one list per item
    change_count: int

    @property
    def empty(self) -> bool:
        return not any(self.items)

    def size(self) -> int:
        return sum(len(data) for item in self.items for _, data in item)


def snapshot(pb=None) -> Snapshot:
    """Every item and every type on the pasteboard, as bytes."""
    pb = pb or general()
    items = []
    for item in pb.pasteboardItems() or []:
        entry = []
        for t in item.types() or []:
            data = item.dataForType_(t)
            if data is not None:
                entry.append((str(t), bytes(data)))
        items.append(entry)
    return Snapshot(items, int(pb.changeCount()))


def restore(snap: Snapshot, pb=None, expected_change: int | None = None) -> bool:
    """Put `snap` back. With `expected_change`, only if nothing has written
    to the pasteboard since Halo did. Returns True if it restored."""
    from AppKit import NSPasteboardItem
    from Foundation import NSData
    pb = pb or general()
    if expected_change is not None and int(pb.changeCount()) != expected_change:
        return False
    pb.clearContents()
    if snap.empty:
        return True
    objects = []
    for entry in snap.items:
        item = NSPasteboardItem.alloc().init()
        for t, data in entry:
            item.setData_forType_(NSData.dataWithBytes_length_(data, len(data)), t)
        objects.append(item)
    return bool(pb.writeObjects_(objects))


def put_text(text: str, pb=None) -> int:
    """Write `text` for a paste. Returns the changeCount after writing, which
    is what restore() compares against."""
    from AppKit import NSPasteboardItem
    from Foundation import NSData
    pb = pb or general()
    pb.clearContents()
    item = NSPasteboardItem.alloc().init()
    item.setString_forType_(text, PLAIN)
    for marker in (TRANSIENT, CONCEALED, AUTO_GENERATED):
        item.setData_forType_(NSData.data(), marker)
    pb.writeObjects_([item])
    return int(pb.changeCount())


def put_text_for_user(text: str, pb=None) -> None:
    """Leave `text` on the clipboard for the user to paste themselves (the
    recovery path). Not transient: they are meant to keep it."""
    pb = pb or general()
    pb.clearContents()
    pb.setString_forType_(text, PLAIN)


def read_text(pb=None) -> str | None:
    pb = pb or general()
    value = pb.stringForType_(PLAIN)
    return str(value) if value is not None else None
